from ..constants.types import type_chart as tc, type_map as tm
from src.utils import fetcher as static_f
from ..constants.structs import objects
from ..constants.requesting import fetch as f
from typing import List

class Weak:
    '''Utility class for finding a type's weaknesses, resistances, and immunities, in that order.'''

    def __init__(self):
        self.dmg_ordering = [tc.super_dmg, tc.resist_dmg, tc.no_dmg]

    @staticmethod
    def remove_special(type: str):
        '''Used for comparing Strings alphabetically without worrying about special characters.'''
        return [c for c in type if c.isalpha()]
    
    def match_dmg_type_two(self, type_1: str, type_2: str, dmg_type: float) -> List:
        '''Finds all the weaknesses and resistances of a dual typed Pokemon. Bolds double resistances or weaknesses.'''
        
        weak_list = []  
        double_effect = tc.super_dmg*2 if dmg_type == tc.super_dmg else tc.resist_dmg/2

        for i in range(tc.num_types):
            t_mat = tc.type_matrix[i]
            calc_dmg = t_mat[tm.t_map[type_1]] * t_mat[tm.t_map[type_2]]

            if calc_dmg == double_effect and dmg_type != 0:
                weak_list.append(f"**{tm.rev_t_map[i].capitalize()}**")   
            elif calc_dmg == dmg_type:
                weak_list.append(tm.rev_t_map[i].capitalize())

        return sorted(weak_list, key=Weak.remove_special)
    
    def match_dmg_type(self, type_1: str, dmg_type: float) -> List:
        '''Finds all the weaknesses and resistances of a single typed Pokemon.'''

        weak_list = []
         
        for i in range(tc.num_types):
            if tc.type_matrix[i][tm.t_map[type_1]] == dmg_type:
                weak_list.append(tm.rev_t_map[i].capitalize())

        return sorted(weak_list)
    
    def build_matrix(self, *args, title) -> List[List]:
        '''Constructs the matrix we will use to print all weaknesses.'''

        built_matrix = []
        func_name = self.match_dmg_type if len(args) == 1 else self.match_dmg_type_two

        for dmg_type in self.dmg_ordering:
            built_matrix.append(func_name(*args, dmg_type))

        return [title, built_matrix]

    def format_matrix(self, title_matrix) -> str:
        '''Formatting the output matrix generated by build matrix.'''

        label_list = ["Weaknesses", "Resistances", "Immunities"]
        answer = ""
        answer += f"{title_matrix[0]}:\n"
        matrix = title_matrix[1]

        for i in range(len(label_list)):
            answer += f"**{label_list[i]}:** {", ".join(matrix[i]) if matrix[i] else "None"}"

            answer += "\n" if i != len(label_list) - 1 else ""

        return answer
    
    def title_type(self, *args):
        '''Titles types properly.'''

        return args[0].title() if len(args) == 1 else f"{args[0].title()}/{args[1].title()}"

    def get_pokemon_type(self, pokemon: str):
        '''Makes an HTTP request to get a Pokemon's type if needed.'''

        return f.fetcher.get_type(pokemon, static_f.Fetcher.request_pokemon(pokemon))
    
    def get_weak(self, *args, title) -> str:
        '''Helper function for getting a list of a Pokemon's weaknesses, resistances, and immunities.'''

        return self.format_matrix(self.build_matrix(*args, title=title))

    def weak(self, *args) -> str:
        '''Returns all of the weaknesses, resistances, and immunities of a given Pokemon.'''

        args = tuple(arg.strip().lower() for arg in args)

        if all(arg in tm.t_map.keys() for arg in args):
            return self.get_weak(*args, title=self.title_type(*args))
                
        if pokemonic_answer := (static_f.Fetcher.pokemonic_get(args[0], f.fetcher.get_type)):
            return self.get_weak(*pokemonic_answer[1], title=f"{pokemonic_answer[0].title()}")
        
        if (sanitized_pokemon := (static_f.Fetcher.sanitize(args[0]))) in objects.pokemon:
            return self.get_weak(*self.get_pokemon_type(sanitized_pokemon)[1], title=f"{args[0].title()}")

        answer = ""
        
        if closest_mon := objects.pokemon.close_match(args[0]):
            answer += f"i dunno know what pokemon {args[0]} is so i'll guess that you meant {closest_mon}\n"
            mon_type = self.get_pokemon_type(closest_mon)[1]
            return answer + self.get_weak(*mon_type, title=f"{closest_mon.title()}")
        
        args_list = [a for a in args]
        
        for i in range(len(args_list)):
            if closest_type := objects.types.close_match(args_list[i]):
                answer += f"i dunno know what type {args_list[0]} is so i'll guess that you meant {closest_type}\n"
                args_list[i] = closest_type

        answer += "\n" if len(answer) > 0 else ""

        if all(arg in tm.t_map.keys() for arg in args_list):
            return answer + self.get_weak(*args_list, title=self.title_type(*args_list))
        
        error = ""
        
        if args[0] not in tm.t_map.keys():
            error += f"i don't think {args[0]} is a type or a pokemon... check your spelling?"

        error += "\n" if len(error) > 0 else ""

        if len(args) == 2 and args[1] not in tm.t_map.keys():
            error += f"i don't think {args[1]} is a move... check your spelling?"

        return error