from ..constants.types import type_chart as tc, type_map as tm
from src.utils import fetcher as static_f
from ..constants.output import weak_res_imm
from ..constants.structs import objects
from ..constants.requesting import fetch as f
from typing import List

class Weak:
    '''Utility class for finding a type's weaknesses, resistances, and immunities, in that order.'''

    def __init__(self):
        self.dmg_ordering = [tc.super_dmg, tc.resist_dmg, tc.no_dmg]
    
    def weak(self, *args: str) -> str:
        '''Returns all of the weaknesses, resistances, and immunities of a given Pokemon.'''

        args = list(arg.strip().lower() for arg in args)

        if all(arg in tm.all_types for arg in args):
            return self.get_weak(self.title_type(*args), *args)
                
        if pokemonic_answer := (static_f.Fetcher.pokemonic_get(args[0], f.fetcher.get_type)):
            return self.get_weak_pokemon(pokemonic_answer[0], *pokemonic_answer[1])
        
        if (sanitized_pokemon := (static_f.Fetcher.sanitize(args[0]))) in objects.pokemon:
            return self.get_weak_pokemon(sanitized_pokemon, *self.get_pokemon_type(sanitized_pokemon)[1])

        answer = ""
        
        if closest_mon := objects.pokemon.close_match(args[0]):
            answer += f"i dunno know what pokemon {args[0]} is so i'll guess that you meant {closest_mon}\n\n"
            return answer + self.get_weak_pokemon(closest_mon, *self.get_pokemon_type(closest_mon)[1])

        for i in range(len(args)):
            if closest_type := objects.types.close_match(args[i]):
                answer += f"i dunno know what type {args[i]} is so i'll guess that you meant {closest_type}\n"
                args[i] = closest_type

        answer += "\n" if len(answer) > 0 else ""

        if all(arg in tm.all_types for arg in args):
            return answer + self.get_weak(self.title_type(*args), *args)
                
        return "\n".join(f"i don't think {arg} is a type or a pokemon... check your spelling?" for arg in args if arg not in tm.all_types)
    
    def match_dmg_type(self, type_1: str, dmg_type: float) -> List:
        '''Finds all the weaknesses and resistances of a single typed Pokemon.'''

        weak_list = []
         
        for i in range(tc.num_types):
            if tc.type_matrix[i][tm.t_map[type_1]] == dmg_type:
                weak_list.append(tm.rev_t_map[i].capitalize())

        return sorted(weak_list)
       
    def match_dmg_type_two(self, type_1: str, type_2: str, dmg_type: float) -> List:
        '''Finds all the weaknesses and resistances of a dual typed Pokemon. Bolds double resistances or weaknesses.'''
        
        weak_list = []  
        double_effect = tc.super_dmg*2 if dmg_type == tc.super_dmg else tc.resist_dmg/2

        for i in range(tc.num_types):
            t_mat = tc.type_matrix[i]
            calc_dmg = t_mat[tm.t_map[type_1]] * t_mat[tm.t_map[type_2]]

            if calc_dmg == double_effect and dmg_type != 0:
                weak_list.append(f"**{tm.rev_t_map[i].capitalize()}**")   
            elif calc_dmg == dmg_type:
                weak_list.append(tm.rev_t_map[i].capitalize())

        return sorted(weak_list, key=Weak.remove_special)

    def build_matrix(self, title: str, *types: str) -> List[List]:
        '''Constructs the matrix we will use to print all weaknesses.'''

        built_matrix = []
        func_name = self.match_dmg_type if len(types) == 1 else self.match_dmg_type_two

        for dmg_type in self.dmg_ordering:
            built_matrix.append(func_name(*types, dmg_type))

        return [title, built_matrix]

    def format_matrix(self, title_matrix: List[List]) -> str:
        '''Formatting the output matrix generated by build matrix.'''

        answer = ""
        answer += f"{title_matrix[0]}:\n"
        matrix = title_matrix[1]

        for i in range(len(weak_res_imm.label_list)):
            answer += f"**{weak_res_imm.label_list[i]}:** {", ".join(matrix[i]) if matrix[i] else "None"}"
            answer += "\n" if i != len(weak_res_imm.label_list) - 1 else ""

        return answer
    
    def get_weak(self, title: str, *types: str) -> str:
        '''Helper function for getting a list of a given type's weaknesses, resistances, and immunities.'''

        return self.format_matrix(self.build_matrix(title, *types))
    
    def get_weak_pokemon(self, pokemon_name: str, *types: str) -> str:
        '''Helper function for getting a list of a Pokemon's weaknesses, resistances, and immunities.'''

        return self.get_weak(self.title_pokemon(pokemon_name, *types), *types)
    
    def get_pokemon_type(self, pokemon: str) -> List:
        '''Makes an HTTP request to get a Pokemon's type if needed.'''

        return f.fetcher.get_type(pokemon, static_f.Fetcher.request_pokemon(pokemon))
    
    def title_type(self, *types: str) -> str:
        '''Titles types properly.'''

        return "/".join(type.title() for type in types)
    
    def title_pokemon(self, pokemon_name: str, *types: str) -> str:
        '''Properly titles a Pokemon and its type.'''

        return f"{pokemon_name.title()} - ({self.title_type(*types)})"

    @staticmethod
    def remove_special(type_name: str) -> str:
        '''Used for comparing Strings alphabetically without worrying about special characters.'''

        return [c for c in type_name if c.isalpha()]